name: Workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  vulnerabilities:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ['python']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Run tests and collect coverage
        run: |
          pip install -r requirements.txt
          coverage run -m unittest
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          file: ./coverage.xml
          verbose: true
